// This file is generated by Slice Machine. Update with care!

import Banner from './Banner';
import BrandVideo from './BrandVideo';
import Brandsponsor from './Brandsponsor';
import ChatWithUs from './ChatWithUs';
import OpenIllustrationCard from './OpenIllustrationCard';
import OurStory from './OurStory';
import SectionCollection from './SectionCollection';
import SectionFollowUs from './SectionFollowUs';
import SectionOpenFashion from './SectionOpenFashion';

export {
	Banner,
	BrandVideo,
	Brandsponsor,
	ChatWithUs,
	OpenIllustrationCard,
	OurStory,
	SectionCollection,
	SectionFollowUs,
	SectionOpenFashion,
};

export const components = {
	banner: Banner,
	brand_video: BrandVideo,
	brandsponsor: Brandsponsor,
	chat_with_us: ChatWithUs,
	open_illustration_card: OpenIllustrationCard,
	our_story: OurStory,
	section_collection: SectionCollection,
	section_follow_us: SectionFollowUs,
	section_open_fashion: SectionOpenFashion,
};
