// This file is generated by Slice Machine. Update with care!

import Banner from './Banner';
import Brandsponsor from './Brandsponsor';
import BrandVideo from './BrandVideo';
import OpenIllustrationCard from './OpenIllustrationCard';
import SectionCollection from './SectionCollection';
import SectionFollowUs from './SectionFollowUs';
import SectionOpenFashion from './SectionOpenFashion';

export {
	Banner,
	Brandsponsor,
	BrandVideo,
	OpenIllustrationCard,
	SectionCollection,
	SectionFollowUs,
	SectionOpenFashion,
};

export const components = {
	banner: Banner,
	brandsponsor: Brandsponsor,
	brand_video: BrandVideo,
	open_illustration_card: OpenIllustrationCard,
	section_collection: SectionCollection,
	section_follow_us: SectionFollowUs,
	section_open_fashion: SectionOpenFashion,
};
